### ISSUE TITLE
Context and Choice Pannel

### ISSUE THREAD

**Issue by khadekirti** [Fen9/WReN#3]
The code does not differentiate between the context and the choice panel. It cumulates both and puts them together into an RN. Is that correct? I don't think that its this way in the original paper

**Comment by WellyZhang** [comment]
Could you please be more specific about what you believe is not right and what the paper says about it? I'm not sure what you mean by "cumulates both and puts them together into an RN".

**Comment by khadekirti** [comment]
Code: WREN.py >> Class WREN 

 - In function "group_panel_embeddings_batch", you have concatenated choice pannels, context panels, and unsqueezed/expanded version of context pannel  

- In the next step (function "forward") this entire group panel embedding batch goes into the RN MLP

However, the research paper, the authors specify the following:

For each choice panel:  

- For each context panel: 

1. Make a RN  MLP of each context pannel to the other context pannels 
 

2. Make a RN MLP of each choice pannel to the other contect pannel

- sum all of 1 and 2 for each choice and send it to another MLP. Get  a output is a single sigmoid unit encoding the “score". 

To quote the research paper,

"WReN model A CNN processes each context panel and an individual answer choice panel independently to produce 9 vector embeddings. This set of embeddings is then passed to an RN, whose output is a single sigmoid unit encoding the “score” for the associated answer choice panel. 8 such passes are made through this network (here we only depict 2 for clarity), one for each answer choice, and the scores are put through a softmax function to determine the model’s predicted answer"

**Comment by WellyZhang** [comment]
According to the ICML [talk](https://vimeo.com/287812787) the authors gave (at 08:22), they use an RN for embeddings for all context panels and one choice, not an RN for each context/choice panel.

This is what we did in the code.
