### ISSUE TITLE
Did you forget of: tagging CNN output in LSTM model?

### ISSUE THREAD

**Issue by odats** [Fen9/WReN#4]
3. Models and Experimental Setup
LSTM

... tagged the CNN’s output with a onehot label indicating the panel’s position (the top left PGM
panel is tagged with label 1, the top-middle PGM panel istagged with label 2 etc.)

**Comment by WellyZhang** [comment]
Thanks for pointing it out. Will fix it soon!

**Comment by WellyZhang** [comment]
Fixed. Thanks!

**Comment by odats** [comment]
Do you think it will improve performance?

**Comment by WellyZhang** [comment]
It probably will as we notice tagging is essential to WReN's performance.
